### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by Lyr3x** [Nesurion/milight-daemon#5] opened 2015-11-08 12:05 UTC
After sending a lot commands to the daemon, it will be very slow, or sometimes the daemon dont work anymore.. I thought the bridge is crashing but i can use the app to control the lights, so the issue is here

**Comment by Nesurion** [comment] 2015-11-09 10:24
I have an idea about this. I need to setup my test env and will get back to you on this.

**Comment by Nesurion** [comment] 2015-11-09 16:40
there was an error in the depending lib go-limitless, the connection after sending a command was not closed. This is fixed now.
Can't reproduce the error anymore. Could you rebuild your daemon and give it a try.

Feel free to mark this issue closed when this works now for you.

**Closed as completed** 2015-11-13 15:44 UTC
